apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: apache
  labels:
    app: apache
    tier: webapp
  namespace: apache
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        kindName: POD
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
